FROM python:3.11-slim

WORKDIR /app/dashboard

COPY dashboard/ /app/dashboard/

RUN pip install streamlit duckdb pandas

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]