services:
  dashboard:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: crdataanalysis101.azurecr.io/dashboard:latest