version: "3.9"

services:
  dwh_pipeline:
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crdataanalysis101.azurecr.io/hr-pipeline:latest