sources:
  - name: job_ads
    schema: staging
    tables:
      - name: stg_ads
        identifier: technical_field_job_ads
        meta: # This metadata specifies the corresponding Dagster asset for this dbt source.
          dagster:
            asset_key: ['dlt_jobads_source_jobads_resource']